//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RepositoryPattern.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anuncios
    {
        public int Id { get; set;  }
        public string Anuncio { get; set; }
        public string Autor { get; set; }
        public string Email { get; set; }
        public int Tipo { get; set; }
    }
}
