//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class comment
    {
        public long idComment { get; set; }
        public string Comment1 { get; set; }
        public Nullable<long> Publicado { get; set; }
        public Nullable<long> idPregunta { get; set; }
    }
}
